Move Across Relayer secrets from AWS Secrets Manager to S3 bucket
LiskHQ/across-relayer pull request #75
Opened 2024-10-04 10:54 UTC by matjazv

### What was the problem?

This PR resolves #LISK-1148.

### How was it solved?

- [x] Environment files for mainnet and testnet were created inside S3 bucket
- [x] Scripts were modified to pull data from S3 instead of AWS Secrets

### How was it tested?

Start the containers locally with the docker dev scripts
Run: `curl --fail http://localhost:3000/healthz` and check container health with `docker ps`

2024-10-04 11:43 UTC, sameersubudhi requested changes

2024-10-04 11:43 UTC, sameersubudhi commented on scripts/lisk/docker/dev/setEnvVariables.sh
> +rm -f .${file_name}
```suggestion
source_env_file_name=across-relayer-dev.env
env_file_name=.${source_env_file_name}

aws s3 cp s3://lisk-envs/$source_env_file_name ${env_file_name}
source ${env_file_name}
rm -f ${env_file_name}
```

2024-10-04 11:43 UTC, sameersubudhi commented on scripts/lisk/docker/setEnvVariables.sh
> +rm -f .${file_name}
```suggestion
source_env_file_name=across-relayer-mainnet.env
env_file_name=.${source_env_file_name}

aws s3 cp s3://lisk-envs/$source_env_file_name ${env_file_name}
source ${env_file_name}
rm -f ${env_file_name}
```

2024-10-04 12:07 UTC, sameersubudhi approved these changes
LGTM! And, works locally as expected. 👍

2024-10-07 02:26 UTC, Incede approved these changes

2024-10-07 07:12 UTC, merged